export const mockDataClientSuccessOwner = [
    {
        "client_success_id": 1,
        "client_success_name": "success 1",
        "client_id": 1,
        "client_name": "client 1",
     },
     {
        "client_success_id": 1,
        "client_success_name": "success 2",
        "client_id": 2,
        "client_name": "client 2",
     }
]

export const mockDataLinehaul = [
    {
        last_updated: new Date(2023, 1, 3),
        injection_date: new Date(2023, 1, 3),
        injection_time: '10:00 AM',
        linehaul_type: 'Middle Mile',
        client_name: 'Hello Fresh',
        client_id: 1,
        linehaul_id: 1,
        parcel_size: 'Small',
        estimated_volume: 100,
        estimated_weight: 100,
        equipment_type: 'Sprinter Van',
        pickup_date: new Date(2023, 1, 3),
        pickup_time: '10:00 AM',
        pickup_region: 'EWR',
        injection_region: 'JFK',
        client_success_name: 'Mary Q.',
        client_linehaul_name: 'John D.',
        notes: 'Notes'
    },
    {
            last_updated: new Date(2023, 1, 3),
            injection_date: new Date(2023, 1, 3),
            injection_time: '10:00 AM',
            linehaul_type: 'Middle Mile',
            client_name: 'Hello Fresh',
            client_id: 1,
            linehaul_id: 1,
            parcel_size: 'Small',
            estimated_volume: 100,
            estimated_weight: 100,
            equipment_type: 'Sprinter Van',
            pickup_date: new Date(2023, 1, 3),
            pickup_time: '10:00 AM',
            pickup_region: 'EWR',
            injection_region: 'JFK',
            client_success_name: 'Mary Q.',
            client_linehaul_name: 'John D.',
            notes: 'Notes'
        },
    {
        last_updated: new Date(2023, 1, 3),
        injection_date: new Date(2023, 1, 3),
        injection_time: '10:00 AM',
        linehaul_type: 'Middle Mile',
        client_name: 'Hello Fresh',
        client_id: 1,
        linehaul_id: 1,
        parcel_size: 'Small',
        estimated_volume: 100,
        estimated_weight: 100,
        equipment_type: 'Sprinter Van',
        pickup_date: new Date(2023, 1, 3),
        pickup_time: '10:00 AM',
        pickup_region: 'EWR',
        injection_region: 'JFK',
        client_success_name: 'Mary Q.',
        client_linehaul_name: 'John D.',
        notes: 'Notes'
    },
{
        last_updated: new Date(2023, 1, 3),
        injection_date: new Date(2023, 1, 3),
        injection_time: '10:00 AM',
        linehaul_type: 'Middle Mile',
        client_name: 'Hello Fresh',
        client_id: 1,
        linehaul_id: 1,
        parcel_size: 'Small',
        estimated_volume: 100,
        estimated_weight: 100,
        equipment_type: 'Sprinter Van',
        pickup_date: new Date(2023, 1, 3),
        pickup_time: '10:00 AM',
        pickup_region: 'EWR',
        injection_region: 'JFK',
        client_success_name: 'Mary Q.',
        client_linehaul_name: 'John D.',
        notes: 'Notes'
    },
{
        last_updated: new Date(2023, 1, 3),
        injection_date: new Date(2023, 1, 3),
        injection_time: '10:00 AM',
        linehaul_type: 'Middle Mile',
        client_name: 'Hello Fresh',
        client_id: 1,
        linehaul_id: 1,
        parcel_size: 'Small',
        estimated_volume: 100,
        estimated_weight: 100,
        equipment_type: 'Sprinter Van',
        pickup_date: new Date(2023, 1, 3),
        pickup_time: '10:00 AM',
        pickup_region: 'EWR',
        injection_region: 'JFK',
        client_success_name: 'Mary Q.',
        client_linehaul_name: 'John D.',
        notes: 'Notes'
    },
{
        last_updated: new Date(2023, 1, 3),
        injection_date: new Date(2023, 1, 3),
        injection_time: '10:00 AM',
        linehaul_type: 'Middle Mile',
        client_name: 'Hello Fresh',
        client_id: 1,
        linehaul_id: 1,
        parcel_size: 'Small',
        estimated_volume: 100,
        estimated_weight: 100,
        equipment_type: 'Sprinter Van',
        pickup_date: new Date(2023, 1, 3),
        pickup_time: '10:00 AM',
        pickup_region: 'EWR',
        injection_region: 'JFK',
        client_success_name: 'Mary Q.',
        client_linehaul_name: 'John D.',
        notes: 'Notes'
    },
{
        last_updated: new Date(2023, 1, 3),
        injection_date: new Date(2023, 1, 3),
        injection_time: '10:00 AM',
        linehaul_type: 'Middle Mile',
        client_name: 'Hello Fresh',
        client_id: 1,
        linehaul_id: 1,
        parcel_size: 'Small',
        estimated_volume: 100,
        estimated_weight: 100,
        equipment_type: 'Sprinter Van',
        pickup_date: new Date(2023, 1, 3),
        pickup_time: '10:00 AM',
        pickup_region: 'EWR',
        injection_region: 'JFK',
        client_success_name: 'Mary Q.',
        client_linehaul_name: 'John D.',
        notes: 'Notes'
    },
{
        last_updated: new Date(2023, 1, 3),
        injection_date: new Date(2023, 1, 3),
        injection_time: '10:00 AM',
        linehaul_type: 'Client Managed',
        client_name: 'Hello Fresh',
        client_id: 1,
        linehaul_id: 1,
        parcel_size: 'Small',
        estimated_volume: 100,
        estimated_weight: 100,
        equipment_type: 'Sprinter Van',
        pickup_date: new Date(2023, 1, 3),
        pickup_time: '10:00 AM',
        pickup_region: 'EWR',
        injection_region: 'JFK',
        client_success_name: 'Mary Q.',
        client_linehaul_name: 'John D.',
        notes: 'Notes'
    },
{
        last_updated: new Date(2023, 1, 3),
        injection_date: new Date(2023, 1, 3),
        injection_time: '10:00 AM',
        linehaul_type: 'Axlehire Managed',
        client_name: 'Hello Fresh',
        client_id: 1,
        linehaul_id: 1,
        parcel_size: 'Small',
        estimated_volume: 100,
        estimated_weight: 100,
        equipment_type: 'Sprinter Van',
        pickup_date: new Date(2023, 1, 3),
        pickup_time: '10:00 AM',
        pickup_region: 'EWR',
        injection_region: 'JFK',
        client_success_name: 'Mary Q.',
        client_linehaul_name: 'John D.',
        notes: 'Notes'
    },
{
        last_updated: new Date(2023, 1, 3),
        injection_date: new Date(2023, 1, 3),
        injection_time: '10:00 AM',
        linehaul_type: 'Middle Mile',
        client_name: 'Hello Fresh',
        client_id: 1,
        linehaul_id: 1,
        parcel_size: 'Small',
        estimated_volume: 100,
        estimated_weight: 100,
        equipment_type: 'Sprinter Van',
        pickup_date: new Date(2023, 1, 3),
        pickup_time: '10:00 AM',
        pickup_region: 'EWR',
        injection_region: 'JFK',
        client_success_name: 'Mary Q.',
        client_linehaul_name: 'John D.',
        notes: 'Notes'
    },
{
        last_updated: new Date(2023, 1, 3),
        injection_date: new Date(2023, 1, 3),
        injection_time: '10:00 AM',
        linehaul_type: 'Axlehire Managed',
        client_name: 'Hello Fresh',
        client_id: 1,
        linehaul_id: 1,
        parcel_size: 'Small',
        estimated_volume: 100,
        estimated_weight: 100,
        equipment_type: 'Sprinter Van',
        pickup_date: new Date(2023, 1, 3),
        pickup_time: '10:00 AM',
        pickup_region: 'EWR',
        injection_region: 'JFK',
        client_success_name: 'Mary Q.',
        client_linehaul_name: 'John D.',
        notes: 'Notes'
    },
{
        last_updated: new Date(2023, 1, 3),
        injection_date: new Date(2023, 1, 3),
        injection_time: '10:00 AM',
        linehaul_type: 'Client Managed',
        client_name: 'Hello Fresh',
        client_id: 1,
        linehaul_id: 1,
        parcel_size: 'Small',
        estimated_volume: 100,
        estimated_weight: 100,
        equipment: 'Sprinter Van',
        pickup_date: new Date(2023, 1, 3),
        pickup_time: '10:00 AM',
        pickup_region: 'EWR',
        injection_region: 'JFK',
        client_success_name: 'Mary Q.',
        notes: 'Notes'
    }
]