export default {
  container: {
    backgroundColor: '#fff',
    marginTop: '16px',
    marginBottom: '20px',
    padding: '16px',
    textAlign: 'left',
    position: 'relative',
  },
  header: {
    color: '#666',
    fontSize: '0.9em',
    marginBottom: '10px',
    marginTop: '18px',
  },
  modalContainer: {
    width: '1000px',
    height: '800px',
    paddingBottom: '60px',
    paddingLeft: '16px',
    paddingRight: '16px',
  },
  modalListStyle: {
    position: 'absolute',
    overflow: 'auto',
    top: '20px',
    bottom: '60px',
    left: '8px',
    right: '8px',
  },
  searchBar: {
    paddingRight: '180px',
    boxSizing: 'border-box',
    position: 'relative',
    width: '100%',
    marginBottom: 15,
  },
  searchButton: {
    position: 'absolute',
    top: 5,
    marginTop: 0,
    paddingRight: 0,
    right: 0,
    width: '170px',
  },
  searchBox: {
    width: '100%',
    marginTop: '5px',
  },
  modalBottom: {
    position: 'absolute',
    width: '100%',
    bottom: 0,
    left: 0,
    padding: '15px 0',
  },
  solutionsListContainer: {
    marginTop: 15,
  },
  solutionsList: {
    flexDirection: 'row',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  searchContainer: {},
  filterContainer: {
    flexDirection: 'row',
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  assignmentHighlight: {
    fontSize: 12,
    backgroundColor: '#fff9e9',
    padding: '7px',
    borderRadius: '3px',
    color: '#737373',
    margin: '0 10px 0 0',
  },
  filterInput: {
    width: '100px',
    marginRight: '5px',
  },
  filterLabel: {
    margin: '0 10px 0 0',
  },
  buttonSelectAll: {
    margin: 0,
    minWidth: '120px',
  },
  title: {
    flex: 1,
    padding: '0 15px',
  },
  halfInput: {
    display: 'inline-flex',
    textAlign: 'left',
    padding: '0 10px',
    boxSizing: 'border-box',
    marginTop: '18px',
    marginBottom: '10px',
  },
  halfLabel: {
    color: '#666',
    fontSize: '0.9em',
    display: 'inline-flex',
    textAlign: 'right',
    boxSizing: 'border-box',
  },
  error: {
    color: '#ff1744',
    fontSize: '14px',
    textAlign: 'left',
  },
};
